---

nameOverride: ""
fullNameOverride: ""

flowg:
  image:
    repository: linksociety/flowg
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

  securityContext: {}
    # allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: false
    # capabilities:
    #   drop:
    #     - ALL

  # Allows to write Tolerations and Taints so the node gets well selected. 
  # Integrates directly into 'tolerations:' section of the StatefulSet tempalte. 
  # To learn more, read https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

  # IMPORTANT NOTE: To make sure scalar values (booleans, int), ALWAYS place them between quotation marks.
  #                 e.g. value: "true", value: "42" instead of value: true or value: 42
  nodeSelectorTolerations:
    - key: "key1"
      operator: "Equal"
      value: "Value1"
      effect: "NoSchedule"
    - key: "key2"
      operator: "Exists"
      effect: "NoExecute"
  

  storage:
    size: 10Gi
    storageClassName: ""

  httpPort: 5080
  mgmtPort: 9113
  
  syslog:
    port: 5514
    protocol: UDP

  https:
    enabled: false

    certificateFrom: {}
      # certmanager: 
      #   privateKey:
      #     algorithm: RSA
      #     encoding: PKCS1
      #     size: 2048

      #   duration: 2160h # 90d
      #   renewBefore: 360h # 15d

      #   isCA: false
      #   usages: 
      #     - server auth

      #   subject:
      #     orgnizations:
      #       - "FlowG"

      #   commonName: logs.example.com
      #   issuerRef: 
      #     name: letsencrypt-prod
      #     kind: ClusterIssuer
      # secretRef: 
      #   name: flowg-tls
      

    mgmt:
      enabled: false

      certificateFrom: {}
        # secretRef:
        #   name: flowg-tls
        
        # certmanager:
        #   privateKey:
        #     algorithm: RSA
        #     encoding: PKCS1
        #     size: 2048
        #   duration: 2160h # 90d
        #   renewBefore: 360h # 15d
        #   isCA: false
        #   usages: 
        #     - server auth
        #   subject:
        #     orgnizations:
        #       - "FlowG"
        #   commonName:
        #   issuerRef:
        #     name: letsencrypt-prod
        #     kind: ClusterIssuer
    

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  service:
    # NodePort, LoadBalancer or ClusterIP 
    type: LoadBalancer

    # Ports inside range 30000-32767
    nodePort:
      httpPort: 30080
      mgmtPort: 32113
      syslogPort: 32514
  

  