---
name: Setup Kubernetes tooling
description: Installs KinD, Helm, and Chart Testing tools and create a cluster
runs:
  using: composite
  steps:
    - name: setup@helm
      uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

    - name: setup@python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: '3.x'
        check-latest: true

    - name: setup@ct
      uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
      with:
        yamale_version: "6.0.0"

    - name: setup@kind
      uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      with:
        version: v0.24.0
        cluster_name: flowg
