---
name: Setup Kubernetes tooling
description: Installs KinD, Helm, and Chart Testing tools and create a cluster
runs:
  using: composite
  steps:
    - name: setup@helm
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4

    - name: setup@python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: '3.x'
        check-latest: true

    - name: setup@ct
      uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b
      with:
        yamale_version: "6.0.0"

    - name: setup@kind
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3
      with:
        version: v0.24.0
        cluster_name: flowg
