version: '3'

includes:
  test: scripts/Taskfile.test.yml
  backend: scripts/Taskfile.backend.yml
  frontend: scripts/Taskfile.frontend.yml
  docker: scripts/Taskfile.docker.yml

tasks:
  build:
    desc: "Build the project"
    cmds:
      - task: "frontend:build"
      - task: "backend:build"

  run:
    desc: "Run the project"
    cmds:
      - ./bin/flowg serve {{.CLI_ARGS}}
    env:
      FLOWG_SECRET_KEY: "s3cr3!"

  doc:
    desc: "Generate documentation"
    cmds:
      - sh scripts/gen_cli_doc.sh

  www:
    desc: "Serve website"
    dir: ./website
    cmds:
      - npm i
      - npm start