version: '3'

includes:
  test: scripts/Taskfile.test.yml
  backend: scripts/Taskfile.backend.yml
  frontend: scripts/Taskfile.frontend.yml
  docker: scripts/Taskfile.docker.yml

tasks:
  build:
    desc: "Build the project"
    cmds:
      - task: "backend:build"
      - task: "frontend:build"

  run:
    desc: "Run the project"
    cmds:
      - ./bin/flowg serve {{.CLI_ARGS}}

  doc:
    desc: "Generate documentation"
    cmds:
      - sh scripts/gen_cli_doc.sh
