version: '3'

includes:
  test: scripts/Taskfile.test.yml
  backend: scripts/Taskfile.backend.yml
  frontend: scripts/Taskfile.frontend.yml
  docker: scripts/Taskfile.docker.yml
  k8s: scripts/Taskfile.k8s.yml

tasks:
  build:
    desc: "Build the project"
    cmds:
      - task: "frontend:build"
      - task: "backend:build"

  run:
    desc: "Run the project"
    cmds:
      - ./bin/flowg-server {{.CLI_ARGS}}
    env:
      FLOWG_SECRET_KEY: "s3cr3!"

  doc:
    desc: "Generate documentation"
    cmds:
      - sh scripts/gen_cli_doc.sh

  www:
    desc: "Serve website"
    dir: ./website
    cmds:
      - npm i
      - npm start

  release:
    desc: "Update version number"
    cmds:
      - echo {{.CLI_ARGS}} > VERSION.txt
      - yq eval '.version = "{{.CLI_ARGS}}"' -i k8s/charts/flowg/Chart.yaml
      - yq eval '.appVersion = "{{.CLI_ARGS}}"' -i k8s/charts/flowg/Chart.yaml
