---

nameOverride: ""
fullnameOverride: ""

flowg:
  # FlowG does not support yet clustering
  # You must specify which Kubernetes node to run it on
  nodeName: ""

  image:
    repository: linksociety/flowg
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets: []

  storage:
    size: 10Gi
    hostPath: /var/lib/flowg/data

  https:
    enabled: false

    certificateFrom: {}
      # secretRef:
      #   name: flowg-tls
      #
      # certmanager:
      #   commonName: logs.example.com
      #   issuerRef:
      #     name: letsencrypt-prod
      #     kind: ClusterIssuer

    mgmt:
      enabled: false

      certificateFrom: {}
        # secretRef:
        #   name: flowg-tls
        #
        # certmanager:
        #   commonName: logs.example.com
        #   issuerRef:
        #     name: letsencrypt-prod
        #     kind: ClusterIssuer

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

fluentd:
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    tag: v1-debian-syslog
    pullPolicy: IfNotPresent
    pullSecrets: []

  logdir: /var/log/pods

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
