[package]
name = "flowg-filterdsl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cc = "1.1"

[dependencies]
anyhow = "1.0"
logos = "0.14.1"
peg = "0.8.4"
serde_json = "1.0.125"
snailquote = "0.3.1"
