---
nameOverride: ""
fullNameOverride: ""

foundationdb:
  # '-1' is none 
  # '0' lets FoundationDB decide how many processes he wants
  processCounts:
    storage: 0
    log: -1
    stateless: -1

  redundancyMode: single

  version: 7.3.69

  resourceRequests:
    worker:
      cpu: 1
      memory: 128Mi
    sidecar:
      cpu: 1
      memory: 128Mi
    
  resourceLimits:
    worker:
      cpu: 1
      memory: 128Mi
    sidecar:
      cpu: 1 
      memory: 128Mi
  
  sidecarContainer: 
    livenessProbe: true
    readinessProbe: false 


  storageRequest: 16Gi

flowg:

  # FLOWG_SECRET_KEY is VITAL if you use more than 1 replicas. 
  # Learn more at https://flowg.cloud/docs/user/advanced/cluster
  secretKey:
    # useExistingSecret allows you to put your own secret for FLOWG_SECRET_KEY.
    # ensure the secret's name and key qre given to 'secretRef'
    useExistingSecret: false

    # secret's name and key are the same for simplicity concerns
    secretRef: flowg-shared-key

  replicas: 4
  image:
    repository: linksociety/flowg
    tag: "" # "v0.63.1-linux-arm"
    pullPolicy: IfNotPresent
    pullSecrets: []
  
  # This section allows to configure FlowG properly
  # Read more at https://flowg.cloud/docs/technical/configuration
  configuration:
    # demoMode: "False"
    logging: 
      verbose: 'True'
      level: "info"

    # The 'seed' functionnality creates a first user (default: root, pw: root)
    # And populates the database with an example dataset, then optionnally changes the credentials. 
    # This requires you to add a secret in the same namespace as FlowG, with:
    # - Initial Username/Password
    # - Reset Username/Password (credentials reset after population)
    # For your configuration to be valid, you MUST provide both username AND password for each type of value.
    # A sole username or password key will NOT be taken in account by the chart
    seed:
      # secretName: flowg-seed-test 
      # initialUsernameKey: initialUsername
      # initialPasswordKey: initialPassword

      # resetUsernameKey: resetUsername
      # resetPasswordKey: resetPassword
    
    

  # Customized annotations in order to enable other software layers to interact with FlowG 
  # (e.g. Prometheus scraping, Traefik directions)
  # Documentation: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: []
    # prometheus.io/scrape: "true"
  serviceAnnotations: [] 
    # traefik.ingress.kubernetes.io/service.passhostheader: "true"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

  securityContext: {}
    # allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: false
    # capabilities:
    #   drop:
    #     - ALL

  # Allows to configure delays for probes (livenessProbe and readinessProbe specified in the templates)
  # Documentation: https://kubernetes.io/docs/concepts/workloads/pods/probes/
  probe:
    livenessProbe: []
      # initialDelaySeconds: 12
      # timeoutSeconds: 10 
      # failureThreshold: 3
      # periodSeconds: 5
    readinessProbe: []
      # initialDelaySeconds: 12
      # timeoutSeconds: 10 
      # failureThreshold: 3
      # periodSeconds: 5

  # Allows to write Tolerations and Taints so the node gets well selected. 
  # Integrates directly into 'tolerations:' section of the StatefulSet tempalte. 
  # To learn more, read https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

  # IMPORTANT NOTE: To make sure scalar values (booleans, int), ALWAYS place them between quotation marks.
  #                 e.g. value: "true", value: "42" instead of value: true or value: 42
  nodeSelectorTolerations:
    # - key: "key1"
    #   operator: "Equal"
    #   value: "Value1"
    #   effect: "NoSchedule"
    # - key: "key2"
    #   operator: "Exists"
    #   effect: "NoExecute"
  

  storage:
    size: 10Gi
    storageClassName: ""

  httpPort: 5080
  
  syslog:
    port: 5514
    protocol: UDP
    # initialAllowedOrigins: "[]"

  https:
    enabled: false

    # certificateFrom:
    #   certmanager: 
    #     privateKey:
    #       algorithm: RSA
    #       encoding: PKCS1
    #       size: 2048

    #     # SAN ; either dnsNames or ipAddresses (mandatory)
    #     # dnsNames: ["logs.example.com"]
    #     ipAddresses: ["127.0.0.1"]
    #     issuerRef: 
    #       name: selfsigned-issuer
    #       kind: Issuer

    #   # secretRef: 
    #   #   name: flowg-tls
      

    mgmt:
      enabled: false

    #   certificateFrom:
    #     certmanager: 
    #       privateKey:
    #         algorithm: RSA
    #         encoding: PKCS1
    #         size: 2048

    #       # SAN ; either dnsNames or ipAddresses (mandatory)
    #       # dnsNames: ["logs.example.com"]
    #       ipAddresses: ["127.0.0.1"]
    #       issuerRef: 
    #         name: selfsigned-issuer
    #         kind: Issuer

    #     # secretRef: 
    #     #   name: flowg-tls
    

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  service:
    # NodePort, LoadBalancer or ClusterIP 
    type: LoadBalancer

    # Ports inside range 30000-32767
    nodePort:
      httpPort: 30080
      syslogPort: 32514
