---
name: Setup FlowG test suite
description: Installs PDM, Hurl and project dependencies
inputs:
  ref:
    description: Git reference (commit, branch or tag)
    required: true
runs:
  using: composite
  steps:
    - name: setup@pdm
      uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0
      with:
        python-version: '3.13'

    - name: setup@sys-deps
      uses: gacts/install-hurl@8c80c69c281b4b618858de1e1a9ce931e9e61c97
      with:
        version: '7.1.0'
        github-token: ${{ github.token }}

    - name: setup@env
      shell: bash
      working-directory: ./tests
      run: pdm install

    - name: download@image
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
      with:
        name: docker-image-${{ inputs.ref }}-linux-amd64

    - name: load@image
      shell: bash
      run: docker load -i image.tar
