---
name: Setup FlowG test suite
description: Installs PDM, Hurl and project dependencies
inputs:
  ref:
    description: Git reference (commit, branch or tag)
    required: true
  ghactor:
    description: GitHub Actor
    required: true
  ghtoken:
    description: GitHub Token
    required: true
runs:
  using: composite
  steps:
    - name: setup@pdm
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.13'

    - name: setup@sys-deps
      uses: gacts/install-hurl@v1

    - name: setup@env
      shell: bash
      working-directory: ./tests
      run: pdm install

    - name: login@docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghactor }}
        password: ${{ inputs.ghtoken }}

    - name: download@artifacts
      shell: bash
      env:
        ARTIFACT_ID: ${{ inputs.ref }}-linux-amd64
      run: |
        docker pull ghcr.io/link-society/flowg/ci-artifacts/docker:${ARTIFACT_ID}
        docker tag ghcr.io/link-society/flowg/ci-artifacts/docker:${ARTIFACT_ID} linksociety/flowg:latest
