---
name: Setup FlowG test suite
description: Installs PDM, Hurl and project dependencies
inputs:
  ref:
    description: Git reference (commit, branch or tag)
    required: true
  ghactor:
    description: GitHub Actor
    required: true
  ghtoken:
    description: GitHub Token
    required: true
runs:
  using: composite
  steps:
    - name: setup@pdm
      uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0
      with:
        python-version: '3.13'

    - name: setup@sys-deps
      uses: gacts/install-hurl@8c80c69c281b4b618858de1e1a9ce931e9e61c97

    - name: setup@env
      shell: bash
      working-directory: ./tests
      run: pdm install

    - name: login@docker
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: ghcr.io
        username: ${{ inputs.ghactor }}
        password: ${{ inputs.ghtoken }}

    - name: download@artifacts
      shell: bash
      env:
        ARTIFACT_ID: ${{ inputs.ref }}-linux-amd64
        ARTIFACT_BASENAME: ghcr.io/link-society/flowg/ci-artifacts
      run: |
        docker pull ${ARTIFACT_BASENAME}/docker:${ARTIFACT_ID}
