// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FABs() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"fixed-action-btn\" style=\"margin-bottom: 5em;\"><button class=\"btn-floating btn-large\"><i class=\"large material-icons\">add</i></button><ul><li><button class=\"btn-floating tooltipped blue flowg-addnode-btn\" data-position=\"left\" data-tooltip=\"Add Transform Node\" data-nodetype=\"transform\"><i class=\"material-icons\">filter_alt</i></button></li><li><button class=\"btn-floating tooltipped red flowg-addnode-btn\" data-position=\"left\" data-tooltip=\"Add Switch Node\" data-nodetype=\"switch\"><i class=\"material-icons\">device_hub</i></button></li><li><button class=\"btn-floating tooltipped purple flowg-addnode-btn\" data-position=\"left\" data-tooltip=\"Add Router Node\" data-nodetype=\"router\"><i class=\"material-icons\">storage</i></button></li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
