apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowg.fullname" . }}
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
  {{- with .Values.flowg.serviceAnnotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.flowg.service.type }}
  selector:
    {{- include "flowg.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.flowg.httpPort }}
      targetPort: 5080
      {{- if has .Values.flowg.service.type (list "NodePort" "LoadBalancer") }}
      nodePort: {{ .Values.flowg.service.nodePort.httpPort }}
      {{- end }}
      protocol: TCP
      {{- if .Values.flowg.https.enabled }}
      appProtocol: https
      {{- else }}
      appProtocol: http
      {{- end }}
    - name: mgmt
      port: {{ .Values.flowg.mgmtPort }}
      targetPort: 9113
      protocol: TCP
      {{- if has .Values.flowg.service.type (list "NodePort" "LoadBalancer") }}
      nodePort: {{ .Values.flowg.service.nodePort.mgmtPort }}
      {{- end }}
      {{- if .Values.flowg.https.mgmt.enabled }}
      appProtocol: https
      {{- else }}
      appProtocol: http
      {{- end }}
    - name: syslog
      port: {{ .Values.flowg.syslog.port }}
      targetPort: 5514
      protocol: {{ .Values.flowg.syslog.protocol }}
      {{- if has .Values.flowg.service.type (list "NodePort" "LoadBalancer") }}
      nodePort: {{ .Values.flowg.service.nodePort.syslogPort }}
      {{- end }}
