---
apiVersion: v1
kind: Namespace
metadata:
  name: flowg-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowg-data-pvc
  namespace: flowg-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowg
  namespace: flowg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flowg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flowg
    spec:
      containers:
        - name: flowg
          image: linksociety/flowg:latest
          ports:
            - containerPort: 5080
              hostPort: 5080
              protocol: TCP
            - containerPort: 5514
              hostPort: 5514
              protocol: UDP
          volumeMounts:
            - name: flowg-data
              mountPath: /data
      volumes:
        - name: flowg-data
          persistentVolumeClaim:
            claimName: flowg-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: flowg
  namespace: flowg-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flowg
  ports:
    - name: http
      port: 5080
      targetPort: 5080
      protocol: TCP
    - name: syslog
      port: 5514
      targetPort: 5514
      protocol: UDP
