---
name: Setup FlowG build chain
description: Installs Go, Rust, Node and Task
inputs:
  rstarget:
    description: Rust target triple
    required: false
    default: x86_64-unknown-linux-gnu
  ghtoken:
    description: GitHub Token
    required: true
runs:
  using: composite
  steps:
    - name: setup@go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: '1.26'
        check-latest: true
        cache: true
        cache-dependency-path: |
          go.sum

    - name: setup@node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '24'
        cache: npm
        cache-dependency-path: |
          web/app/package-lock.json
          website/package-lock.json
          docs/slides/package-lock.json

    - name: setup@rust
      uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      with:
        target: ${{ inputs.rstarget }}
        cache: true
        cache-workspaces: |
          internal/util/langs/vrl/rust-crate/

    - name: setup@task
      uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
      with:
        repo-token: ${{ inputs.ghtoken }}
