---
name: Setup FlowG build chain
description: Installs Go, Rust, Node and Task
inputs:
  rstarget:
    description: Rust target triple
    required: false
    default: x86_64-unknown-linux-gnu
  ghtoken:
    description: GitHub Token
    required: true
runs:
  using: composite
  steps:
    - name: setup@go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version: '1.25'

    - name: setup@node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      with:
        node-version: '24'

    - name: setup@rust
      uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
      with:
        target: ${{ inputs.rstarget }}

    - name: setup@task
      uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
      with:
        repo-token: ${{ inputs.ghtoken }}
