apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flowg.fullname" . }}-data-pvc
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.flowg.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.flowg.storage.size }}
