[package]
name = "flowg-filterdsl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cc = "1.2"

[dependencies]
anyhow = "1.0"
logos = "0.15.0"
peg = "0.8.5"
serde_json = "1.0.139"
snailquote = "0.3.1"
