{{- if .Values.flowg.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowg.serviceAccountName" . }}
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
  {{- with .Values.flowg.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
  name: {{ include "flowg.fullname" . }}-role
rules:
  - apiGroups: ["apps.foundationdb.org"] 
    resources:
      - foundationdbclusters
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flowg.fullname" . }}-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flowg.fullname" . }}-role
subjects:
- namespace: {{ .Release.Namespace }} 
  kind: ServiceAccount
  name: {{ include "flowg.fullname" . }}