apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowg.fullname" . }}-mgmt
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
  {{- with .Values.flowg.serviceAnnotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "flowg.selectorLabels" . | nindent 4 }}
  ports:
    - name: mgmt
      port: 9113
      targetPort: 9113
      protocol: TCP
      {{- if .Values.flowg.https.mgmt.enabled }}
      appProtocol: https
      {{- else }}
      appProtocol: http
      {{- end }}
