---
{{- if not .Values.flowg.secretKey.useExistingSecret }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.flowg.secretKey.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flowg.secretKey.secretRef }}
data:
  {{- if $existingSecret }}
  {{ .Values.flowg.secretKey.secretRef }}: {{ index $existingSecret.data .Values.flowg.secretKey.secretRef }}
  {{- else }}
  {{ .Values.flowg.secretKey.secretRef }}: {{ b64enc (randAlphaNum 12) }}
  {{- end }}
{{- end }}
