{{- if .Values.flowg.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowg.serviceAccountName" . }}
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
  {{- with .Values.flowg.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
