{{- if .Values.fluentd.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd.serviceAccountName" . }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  {{- with .Values.fluentd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
