// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"link-society.com/flowg/internal/auth"
)

type UserInfoProps struct {
	User *auth.User
}

func UserInfo(props UserInfoProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"col s12 m6 h-full\"><article class=\"card h-full flex flex-col p-0\"><section class=\"card-content p-0 h-0 flex-grow flex-shrink flex flex-col\"><header class=\"\n            flex flex-row items-center\n            p-3\n            blue lighten-2\n            white-text\n          \"><p class=\"card-title flex-grow mb-0 font-semibold\">Profile</p></header><main class=\"flex-grow flex-shrink h-0 overflow-auto p-3\"><section class=\"section\"><div class=\"input-field\"><input id=\"username\" type=\"text\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `apps/account/templates/components/user_info.templ`, Line: 32, Col: 38}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" disabled> <label for=\"username\" class=\"active\">Username</label></div><p class=\"font-semibold\">Roles:</p><div class=\"w-full flex flex-row gap-2 py-1 items-center justify-start\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, role := range props.User.Roles {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"grey lighten-2 z-depth-1 px-2 py-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(role)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `apps/account/templates/components/user_info.templ`, Line: 43, Col: 23}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></section><div class=\"divider\"></div><form class=\"section row flex flex-row items-center\" hx-post=\"/web/account/change-password/\" hx-swap=\"none\"><div class=\"input-field col s12 m5\"><i class=\"material-icons prefix\">lock</i> <input id=\"old_password\" type=\"password\" name=\"old_password\" required> <label for=\"old_password\">Old Password</label></div><div class=\"input-field col s12 m5\"><i class=\"material-icons prefix\">lock</i> <input id=\"new_password\" type=\"password\" name=\"new_password\" required> <label for=\"new_password\">New Password</label></div><div class=\"col s12 m2\"><button class=\"waves-effect waves-light btn-small\" type=\"submit\"><i class=\"material-icons\">check</i></button></div></form></main></section></article></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
