---
apiVersion: v1
kind: Secret
metadata: 
  name: flowg-seed-test
  namespace: flowg-singlenode-test
type: Opaque
stringData: 
  initialUsername: user
  initialPassword: user
  resetUsername: classroot
  resetPassword: music 
