apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "flowg.fullname" . }}-data-pv
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "flowg.fullname" . }}-storage
  capacity:
    storage: {{ .Values.flowg.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.flowg.storage.hostPath }}

