apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "flowg.fullname" . }}-storage
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
