apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "flowg.fullname" . }}
  labels:
    {{- include "flowg.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "flowg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flowg.labels" . | nindent 8 }}
    spec:
      {{- with .Values.flowg.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flowg.serviceAccountName" . }}
      containers:
        - name: flowg
          image: "{{ .Values.flowg.image.repository }}:{{ .Values.flowg.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.flowg.image.pullPolicy }}"
          args:
          {{- if .Values.flowg.https.enabled }}
            - --http-tls
            - --http-tls-cert=/data/ssl/tls.crt
            - --http-tls-key=/data/ssl/tls.key
          {{- end }}
          {{- if .Values.flowg.https.mgmt.enabled }}
            - --mgmt-tls
            - --mgmt-tls-cert=/data/ssl/mgmt/tls.crt
            - --mgmt-tls-key=/data/ssl/mgmt/tls.key
          {{- end }}
          env:
            - name: FLOWG_CLUSTER_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FLOWG_CLUSTER_FORMATION_STRATEGY
              value: "k8s"
            - name: FLOWG_CLUSTER_FORMATION_K8S_SERVICE_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: FLOWG_CLUSTER_FORMATION_K8S_SERVICE_NAME
              value: {{ include "flowg.fullname" . }}
            - name: FLOWG_CLUSTER_FORMATION_K8S_SERVICE_PORT_NAME
              value: mgmt
          ports:
            - containerPort: 5080
              hostPort: 5080
              protocol: TCP
            - containerPort: 9113
              hostPort: 9113
              protocol: TCP
            - containerPort: 5514
              hostPort: 5514
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /health
              port: 9113
          readinessProbe:
            httpGet:
              path: /health
              port: 9113
          resources:
            {{- toYaml .Values.flowg.resources | nindent 12 }}
          volumeMounts:
            - name: flowg-data
              mountPath: /data
          {{- if and .Values.flowg.https.enabled (or .Values.flowg.https.certificateFrom.certmanager .Values.flowg.https.certificateFrom.secretRef) }}
            - name: flowg-tls
              mountPath: /data/ssl
          {{- end }}
          {{- if and .Values.flowg.https.mgmt.enabled (or .Values.flowg.https.mgmt.certificateFrom.certmanager .Values.flowg.https.mgmt.certificateFrom.secretRef) }}
            - name: flowg-tls-mgmt
              mountPath: /data/ssl/mgmt
          {{- end }}
      volumes:
        - name: flowg-data
          persistentVolumeClaim:
            claimName: {{ include "flowg.fullname" . }}-data-pvc
      {{- if and .Values.flowg.https.enabled .Values.flowg.https.certificateFrom.certmanager }}
        - name: flowg-tls
          secret:
            secretName: {{ include "flowg.fullname" . }}-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
      {{- else if and .Values.flowg.https.enabled .Values.flowg.https.certificateFrom.secretRef }}
        - name: flowg-tls
          secret:
            secretName: {{ .Values.flowg.https.certificateFrom.secretRef.name }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
      {{- end }}
      {{- if and .Values.flowg.https.mgmt.enabled .Values.flowg.https.mgmt.certificateFrom.certmanager }}
        - name: flowg-tls-mgmt
          secret:
            secretName: {{ include "flowg.fullname" . }}-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
      {{- else if and .Values.flowg.https.mgmt.enabled .Values.flowg.https.mgmt.certificateFrom.secretRef }}
        - name: flowg-tls-mgmt
          secret:
            secretName: {{ .Values.flowg.https.mgmt.certificateFrom.secretRef.name }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
      {{- end }}
