{{- if and .Values.flowg.https.enabled .Values.flowg.https.certificateFrom.certmanager -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "flowg.fullname" . }}-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "flowg.fullname" . }}-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  subject:
    organizations:
      - "FlowG"

  commonName: {{ .Values.flowg.https.certificateFrom.certmanager.commonName }}
  dnsNames:
    - {{ .Values.flowg.https.certificateFrom.certmanager.commonName }}

  {{- with .Values.flowg.https.certificateFrom.certmanager.issuerRef }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
