---
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.flowg.sharedKeySecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flowg.sharedKeySecretRef }}
data:
  {{- if $existingSecret }}
  {{ .Values.flowg.sharedKeySecretRef }}: {{ index $existingSecret.data .Values.flowg.sharedKeySecretRef }}
  {{- else }}
  {{ .Values.flowg.sharedKeySecretRef }}: {{ b64enc (randAlphaNum 12) }}
  {{- end }}
