---
name: build-website

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  ARTIFACT_ID: ${{ inputs.ref }}
  ARTIFACT_BASENAME: ghcr.io/link-society/flowg/ci-artifacts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ inputs.ref }}

      - name: cache@build
        id: cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          key: website-${{ env.ARTIFACT_ID }}
          path: website/build

      - name: setup@buildchain
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-buildchain
        with:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: download-doc-cli@artifact
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: doc-cli-${{ inputs.ref }}-linux-amd64
          path: website/docs/technical/cli

      - name: download-doc-openapi@artifact
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: doc-openapi-${{ inputs.ref }}-linux-amd64
          path: website/src

      - name: build@website
        if: steps.cache.outputs.cache-hit != 'true'
        run: task www:build

      - name: upload@artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: website-${{ env.ARTIFACT_ID }}
          path: website/build
          retention-days: 1
