---
name: build-docker

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true

permissions:
  contents: write

jobs:
  docker:
    strategy:
      matrix:
        include:
          - ghrunner: ubuntu-latest
            docker_image_tag_suffix: ""
            arch: "amd64"
            os: "linux"
          - ghrunner: ubuntu-24.04-arm
            docker_image_tag_suffix: "-linux-arm"
            arch: "arm64"
            os: "linux"

    runs-on: ${{ matrix.ghrunner }}

    steps:
      - name: checkout@scm
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: setup@docker
        uses: docker/setup-buildx-action@v3

      - name: login@docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: build@docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/flowg.dockerfile
          build-args: |
            UPX_ARCH=${{ matrix.arch }}
            UPX_OS=${{ matrix.os }}
          tags: |
            linksociety/flowg:latest${{ matrix.docker_image_tag_suffix }}
            linksociety/flowg:${{ github.event.release.tag_name }}${{ matrix.docker_image_tag_suffix }}
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
