---
name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@v4

      - name: setup@docker
        uses: docker/setup-buildx-action@v3

      - name: build@docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/flowg.dockerfile
          tags: "linksociety/flowg:latest"
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: setup@test
        uses: gacts/install-hurl@v1

      - name: e2e@test
        working-directory: ./tests/e2e
        run: sh ./run.sh

      - name: report@test
        uses: mikepenz/action-junit-report@v4
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          report_paths: "./tests/e2e/reports/junit.xml"
          include_passed: true
          fail_on_failure: true
