---
name: build-website

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  ARTIFACT_ID: ${{ inputs.ref }}
  ARTIFACT_BASENAME: ghcr.io/link-society/flowg/ci-artifacts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ inputs.ref }}

      - name: cache@build
        id: cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: website-${{ env.ARTIFACT_ID }}
          path: website/build

      - name: setup@buildchain
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-buildchain
        with:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: download-doc-cli@artifact
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: doc-cli-${{ inputs.ref }}-linux-amd64
          path: website/docs/technical/cli

      - name: download-doc-openapi@artifact
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: doc-openapi-${{ inputs.ref }}-linux-amd64
          path: website/src

      - name: build@website
        if: steps.cache.outputs.cache-hit != 'true'
        run: task www:build

      - name: upload@artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: website-${{ env.ARTIFACT_ID }}
          path: website/build
          retention-days: 1
