---
name: ci-package

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  checks: write
  pull-requests: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: setup@docker
        uses: docker/setup-buildx-action@v3

      - name: build@docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/flowg.dockerfile
          tags: "linksociety/flowg:latest"
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/oci-flowg.tar

      - name: upload@artifact
        uses: actions/upload-artifact@v5
        with:
          name: oci-flowg
          path: /tmp/oci-flowg.tar
          retention-days: 1

  test-e2e-api:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout@scm
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: download@artifact
        uses: actions/download-artifact@v6
        with:
          name: oci-flowg
          path: /tmp

      - name: load@docker
        run: docker load --input /tmp/oci-flowg.tar

      - name: setup@pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'

      - name: setup@sys-deps
        uses: gacts/install-hurl@v1

      - name: setup@env
        working-directory: ./tests
        run: pdm install

      - name: run@test
        working-directory: ./tests
        run: pdm run pytest
        env:
          FLOWG_TEST_SUITES: api

      - name: report@test
        uses: mikepenz/action-junit-report@v5
        if: ${{ github.event_name == 'pull_request_target' && (success() || failure()) }}
        with:
          report_paths: "./tests/reports/api/junit.xml"
          include_passed: true
          check_name: "API End-To-End Test Report"
          job_summary: true
          comment: true
          updateComment: true
          fail_on_failure: true

  test-e2e-web:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout@scm
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: download@artifact
        uses: actions/download-artifact@v6
        with:
          name: oci-flowg
          path: /tmp

      - name: load@docker
        run: docker load --input /tmp/oci-flowg.tar

      - name: setup@pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'

      - name: setup@sys-deps
        run: sudo apt install libasound2t64  # required for Firefox webdriver

      - name: setup@env
        working-directory: ./tests
        run: pdm install

      - name: run@test
        working-directory: ./tests
        run: pdm run pytest
        env:
          FLOWG_TEST_SUITES: web

      - name: report@test
        uses: joonvena/robotframework-reporter-action@v2.5
        if: ${{ github.event_name == 'pull_request_target' && (success() || failure()) }}
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: "./tests/reports/web/"

      - name: report-success@status
        uses: guibranco/github-status-action-v2@v1
        if: ${{ github.event_name == 'pull_request_target' && success() }}
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Web End-To-End Test Report'
          description: 'Passed'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}

      - name: report-failure@status
        uses: guibranco/github-status-action-v2@v1
        if: ${{ github.event_name == 'pull_request_target' && failure() }}
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Web End-To-End Test Report'
          description: 'Failure'
          state: 'failure'
          sha: ${{ github.event.pull_request.head.sha }}

      - name: upload-logs@artifact
        if: ${{ github.event_name == 'pull_request_target' && failure() }}
        uses: actions/upload-artifact@v5
        with:
          name: web-e2e-reports
          path: "./tests/reports/web/"
          retention-days: 1

      - name: report@fail
        if: ${{ github.event_name == 'pull_request_target' && failure() }}
        run: exit 1

  test-e2e-consul:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout@scm
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: download@artifact
        uses: actions/download-artifact@v6
        with:
          name: oci-flowg
          path: /tmp

      - name: load@docker
        run: docker load --input /tmp/oci-flowg.tar

      - name: setup@pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'

      - name: setup@sys-deps
        uses: gacts/install-hurl@v1

      - name: setup@env
        working-directory: ./tests
        run: pdm install

      - name: run@test
        working-directory: ./tests
        run: pdm run pytest
        env:
          FLOWG_TEST_SUITES: consul

      - name: report@test
        uses: mikepenz/action-junit-report@v5
        if: ${{ github.event_name == 'pull_request_target' && (success() || failure()) }}
        with:
          report_paths: "./tests/reports/consul/junit.xml"
          include_passed: true
          check_name: "Consul End-To-End Test Report"
          job_summary: true
          comment: true
          updateComment: true
          fail_on_failure: true

  test-k8s:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout@scm
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: download@artifact
        uses: actions/download-artifact@v6
        with:
          name: oci-flowg
          path: /tmp

      - name: setup@k8s
        uses: ./.github/actions/setup-k8s

      - name: load@k8s
        run: kind load image-archive /tmp/oci-flowg.tar --name flowg

      - name: lint@helm
        run: ct lint --chart-dirs ./k8s/charts --charts ./k8s/charts/flowg --validate-maintainers=false

      - name: test@helm
        run: |
          set -ex
          kubectl get ns flowg-system || kubectl create ns flowg-system
          ct install \
            --chart-dirs ./k8s/charts \
            --charts ./k8s/charts/flowg \
            --namespace flowg-system \
            --helm-extra-set-args '--set=flowg.image.tag=latest --set=flowg.image.pullPolicy=Never --wait'
