---
name: deploy-website

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: setup@oras
        uses: oras-project/setup-oras@v1

      - name: login@oras
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: download@oras
        env:
            ARTIFACT_ID: ${{ inputs.ref }}
        run: |
          oras pull ghcr.io/link-society/flowg/ci-artifacts/website:${ARTIFACT_ID}

      - name: upload@artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/build

      - name: deploy@pages
        id: deployment
        uses: actions/deploy-pages@v4
