---
name: deploy-website

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  ARTIFACT_ID: ${{ inputs.ref }}
  ARTIFACT_BASENAME: ghcr.io/link-society/flowg/ci-artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: setup@oras
        uses: oras-project/setup-oras@38de303aac69abb66f3e6255b7198bff35f323e3

      - name: login@oras
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf '%s' "${GITHUB_TOKEN}" | oras login ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: download@oras
        run: |
          oras pull ${ARTIFACT_BASENAME}/website:${ARTIFACT_ID}

      - name: upload@artifacts
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: ./website/build

      - name: deploy@pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
