---
name: release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@v4

      - name: setup-qemu@docker
        uses: docker/setup-qemu-action@v3

      - name: setup-buildx@docker
        uses: docker/setup-buildx-action@v3

      - name: login@docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build@docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/flowg.dockerfile
          tags: |
            linksociety/flowg:latest
            linksociety/flowg:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
