---
name: release-docker

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: amd64
      os:
        required: false
        type: string
        default: linux
      docker-image-tag-suffix:
        required: false
        type: string
        default: ""

permissions:
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: login-ghcr@docker
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: login-dockerhub@docker
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: publish@docker
        env:
          ARTIFACT_ID: ${{ inputs.ref }}-${{ inputs.os }}-${{ inputs.arch }}
          DOCKERHUB_TAG_LATEST: latest${{ inputs.docker-image-tag-suffix }}
          DOCKERHUB_TAG_VERSION: ${{ inputs.version }}${{ inputs.docker-image-tag-suffix }}
        run: |
          docker pull ghcr.io/link-society/flowg/ci-artifacts/docker:${ARTIFACT_ID}
          docker tag ghcr.io/link-society/flowg/ci-artifacts/docker:${ARTIFACT_ID} linksociety/flowg:${DOCKERHUB_TAG_LATEST}
          docker tag ghcr.io/link-society/flowg/ci-artifacts/docker:${ARTIFACT_ID} linksociety/flowg:${DOCKERHUB_TAG_VERSION}

          docker push linksociety/flowg:${DOCKERHUB_TAG_LATEST}
          docker push linksociety/flowg:${DOCKERHUB_TAG_VERSION}
