---
name: release

on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        include:
          - ghrunner: ubuntu-latest
            docker_image_tag_suffix: ""
          - ghrunner: ubuntu-24.04-arm
            docker_image_tag_suffix: "-linux-arm"

    runs-on: ${{ matrix.ghrunner }}

    steps:
      - name: checkout@scm
        uses: actions/checkout@v4

      - name: setup@docker
        uses: docker/setup-buildx-action@v3

      - name: login@docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build@docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/flowg.dockerfile
          tags: |
            linksociety/flowg:latest${{ matrix.docker_image_tag_suffix }}
            linksociety/flowg:${{ github.event.release.tag_name }}${{ matrix.docker_image_tag_suffix }}
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
