---
name: release-binary

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string
      goos:
        required: false
        type: string
        default: linux
      goarch:
        required: false
        type: string
        default: amd64

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: setup@oras
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6

      - name: login@oras
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf '%s' "${GITHUB_TOKEN}" | oras login ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: download@oras
        env:
          ARTIFACT_ID: ${{ inputs.ref }}-${{ inputs.goos }}-${{ inputs.goarch }}
        run: |
          oras pull ghcr.io/link-society/flowg/ci-artifacts/binaries:${ARTIFACT_ID}

      - name: upload@assets
        run: |
          tar -czf ${ARCHIVE_NAME} bin/ LICENSE.txt
          gh release upload ${RELEASE_NAME} ${ARCHIVE_NAME}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHIVE_NAME: flowg-${{ inputs.version }}-${{ inputs.goos }}-${{ inputs.goarch }}.tar.gz
          RELEASE_NAME: ${{ inputs.version }}
