---
name: test-e2e

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      pr:
        required: false
        type: string

jobs:
  api:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
      checks: write
      pull-requests: write
      statuses: write

    steps:
      - name: checkout@scm
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: "${{ inputs.ref }}"

      - name: setup@testsuite
        uses: ./.github/actions/setup-testsuite
        with:
          ref: ${{ inputs.ref }}
          ghactor: ${{ github.actor }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: run@testsuite
        uses: ./.github/actions/run-hurl-testsuite
        with:
          ref: ${{ inputs.ref }}
          pr: ${{ inputs.pr }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
          testsuite: api
          checkname: "API End-To-End Test Report"

  web:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
      checks: write
      pull-requests: write
      statuses: write

    steps:
      - name: checkout@scm
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: "${{ inputs.ref }}"

      - name: setup@testsuite
        uses: ./.github/actions/setup-testsuite
        with:
          ref: ${{ inputs.ref }}
          ghactor: ${{ github.actor }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: run@testsuite
        uses: ./.github/actions/run-robotframework-testsuite
        with:
          ref: ${{ inputs.ref }}
          pr: ${{ inputs.pr }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
          testsuite: web
          checkname: "Web End-To-End Test Report"

  consul:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
      checks: write
      pull-requests: write
      statuses: write

    steps:
      - name: checkout@scm
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: "${{ inputs.ref }}"

      - name: setup@testsuite
        uses: ./.github/actions/setup-testsuite
        with:
          ref: ${{ inputs.ref }}
          ghactor: ${{ github.actor }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: run@testsuite
        uses: ./.github/actions/run-hurl-testsuite
        with:
          ref: ${{ inputs.ref }}
          pr: ${{ inputs.pr }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
          testsuite: consul
          checkname: "Consul End-To-End Test Report"

  dns:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      checks: write
      pull-requests: write
      statuses: write

    env:
      ARTIFACT_ID: ${{ inputs.ref }}-linux-amd64
      ARTIFACT_FLOWG_BASENAME: ghcr.io/link-society/flowg/ci-artifacts/docker
      ARTIFACT_DNSSERVER_BASENAME: ghcr.io/link-society/flowg/tests-artifacts/dns-server
      ARTIFACT_DNSCLIENT_BASENAME: ghcr.io/link-society/flowg/tests-artifacts/dns-client

    steps:
      - name: checkout@scm
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: "${{ inputs.ref }}"

      - name: setup@testsuite
        uses: ./.github/actions/setup-testsuite
        with:
          ref: ${{ inputs.ref }}
          ghactor: ${{ github.actor }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: setup@docker
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: build-dns-server@docker
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          file: ./tests/config/dns/dns-server.dockerfile
          tags: ${{ env.ARTIFACT_DNSSERVER_BASENAME }}:${{ env.ARTIFACT_ID }}
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build-dns-client@docker
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          file: ./tests/config/dns/dns-client.dockerfile
          build-args: |
            BASEIMAGE=${{ env.ARTIFACT_FLOWG_BASENAME }}:${{ env.ARTIFACT_ID }}
          tags: ${{ env.ARTIFACT_DNSCLIENT_BASENAME }}:${{ env.ARTIFACT_ID }}
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: download-dns@artifacts
        shell: bash
        env:
          DOCKER_DNSSERVER_IMAGE: ${{ env.ARTIFACT_DNSSERVER_BASENAME }}:${{ env.ARTIFACT_ID }}
          DOCKER_DNSCLIENT_IMAGE: ${{ env.ARTIFACT_DNSCLIENT_BASENAME }}:${{ env.ARTIFACT_ID }}
        run: |
          docker pull ${DOCKER_DNSSERVER_IMAGE}
          docker pull ${DOCKER_DNSCLIENT_IMAGE}

          echo "DNSSERVER_TEST_DOCKER_IMAGE_NAME=${DOCKER_DNSSERVER_IMAGE}" >> $GITHUB_ENV
          echo "DNSCLIENT_TEST_DOCKER_IMAGE_NAME=${DOCKER_DNSCLIENT_IMAGE}" >> $GITHUB_ENV

      - name: run@testsuite
        uses: ./.github/actions/run-hurl-testsuite
        with:
          ref: ${{ inputs.ref }}
          pr: ${{ inputs.pr }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
          testsuite: dns
          checkname: "DNS End-To-End Test Report"

  k8s:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
      checks: write
      pull-requests: write
      statuses: write

    steps:
      - name: checkout@scm
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: "${{ inputs.ref }}"

      - name: setup@testsuite
        uses: ./.github/actions/setup-testsuite
        with:
          ref: ${{ inputs.ref }}
          ghactor: ${{ github.actor }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: setup@k8s
        uses: ./.github/actions/setup-k8s

      - name: run@testsuite
        uses: ./.github/actions/run-k8s-testsuite
        with:
          ref: ${{ inputs.ref }}
          pr: ${{ inputs.pr }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
          checkname: "Kubernetes End-To-End Test Report"
