// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar(currentNav string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"blue darken-3\"><div class=\"nav-wrapper\"><a href=\"/\" class=\"brand-logo left\" style=\"padding-left: 0.25em;\">FlowG</a><ul id=\"nav-mobile\" class=\"right hide-on-med-and-down\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch currentNav {
		case "streams":
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li class=\"active\"><a><i class=\"left material-icons\">list</i> Streams</a></li><li><a href=\"/dashboard/transformers\"><i class=\"left material-icons\">filter_alt</i> Transformers</a></li><li><a href=\"/dashboard/pipelines\"><i class=\"left material-icons\">settings</i> Pipelines</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "transformers":
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><a href=\"/dashboard/streams\"><i class=\"left material-icons\">list</i> Streams</a></li><li class=\"active\"><a><i class=\"left material-icons\">filter_alt</i> Transformers</a></li><li><a href=\"/dashboard/pipelines\"><i class=\"left material-icons\">settings</i> Pipelines</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "pipelines":
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><a href=\"/dashboard/streams\"><i class=\"left material-icons\">list</i> Streams</a></li><li><a href=\"/dashboard/transformers\"><i class=\"left material-icons\">filter_alt</i> Transformers</a></li><li class=\"active\"><a><i class=\"left material-icons\">settings</i> Pipelines</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><a href=\"/dashboard/streams\"><i class=\"left material-icons\">list</i> Streams</a></li><li><a href=\"/dashboard/transformers\"><i class=\"left material-icons\">filter_alt</i> Transformers</a></li><li><a href=\"/dashboard/pipelines\"><i class=\"left material-icons\">settings</i> Pipelines</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</ul></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
